### ISSUE TITLE
(half of) ongaku links not working

### ISSUE THREAD

**Issue by MrZilty** [VocaDB/vocadb#1704] opened 2024-03-05 12:26 UTC
"Could not find id element on page" still showing up while trying to add piapro ongaku link to entries.

**Comment by Shiroizu** [comment] 2024-03-05 12:36
Duplicate of #1685

**Comment by Shiroizu** [comment] 2024-03-05 12:36
> "Could not find id element on page" still showing up while trying to add piapro ongaku link to entries.

Could you provide some example links and entries?

**Comment by MrZilty** [comment] 2024-03-05 12:38
> > "Could not find id element on page" still showing up while trying to add piapro ongaku link to entries.
> 
> Could you provide some example links and entries?

presumably one of the example entries considering they're putting the piapro link in artist's personal description instead : https://vocadb.net/S/592456

**Comment by MrZilty** [comment] 2024-03-05 12:45
though if you mean ongoku links, one of the examples would be between みくみく♪わーるど (https://piapro.jp/t/uL0r) and 相死相哀アプリオリ (https://piapro.jp/content/07bojgtpfkih3tul)
my guess would be that that the 4 letters links can't be added, as for the longer letters links, i can't find a way to retrieve it instead of the 4 letters link.

**Comment by FinnRG** [comment] 2024-03-05 14:38
Piapro seems to have updated their page again. Atleast fixing this should be easy.

**Closed** 2024-03-06 22:10 UTC
Labels: duplicate, content: songs, media, adding/editing entries, external websites
