### ISSUE TITLE
Songs in "liked songs" view should be sorted by rating date by default

### ISSUE THREAD

**Issue by jukkahyv** [VocaDB/vocadb#1076] opened 2022-03-05 13:41 UTC
I noticed the default sort order was changed to "name". Is there a reason? I used this view a lot to get songs that I have rated recently.

1. Go to profile page
2. Go to "liked songs" tab

Songs should be sorted by "rating date". Instead, songs are sorted by "name".

**Comment by ycanardeau** [comment] 2022-03-05 14:04
Duplicate of #1070. Caused by #1065.

**Closed by ycanardeau** 2022-03-05 14:04 UTC
Labels: songs
