### ISSUE TITLE
Wrong descriptions when hovering over tags

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#771] opened 2021-02-16 19:36 UTC
**Website**
VocaDB

**Describe the bug**
Whenever I or other user hover over a tag only one description shows up. Not the right descriptions for the tags and they will appear for every tag. 
For example in my case it is like this:
![grafik](https://user-images.githubusercontent.com/52045122/108112410-534ea380-7096-11eb-83d0-fe3217025611.png)
![grafik](https://user-images.githubusercontent.com/52045122/108112457-695c6400-7096-11eb-970d-1e1c23b4e240.png)

**Comment by riipah** [comment] 2021-02-16 19:37
Duplicate of #768

**Closed** 2021-02-16 19:45 UTC
Labels: content: tags
