### ISSUE TITLE
The thumbnail images of group members are not displayed

### ISSUE THREAD

**Issue by hikaru-soeda** [VocaDB/vocadb#1052] opened 2022-01-25 07:37 UTC
**Website**
VocaDB

**Describe the bug**
The thumbnail images of the members of an artist page whose Type is Group (Circle, Label, Other group) are not displayed.

**To Reproduce**
Circle: https://vocadb.net/Ar/3188
Label: https://vocadb.net/Ar/2347
Other group: https://vocadb.net/Ar/86689

**Expected behavior**
The main picture of the artist page for each member of the group should be displayed.

**Screenshots**
https://vocadb.net/Ar/86689
![2022-01-25 (2)](https://user-images.githubusercontent.com/76765993/150930693-084dbf84-fb5a-4423-adb6-e702511f3acb.png)

**Comment by ycanardeau** [comment] 2022-01-25 14:00
Caused by #1047, and fixed by ae541f6. Now that we use `ArtistForApiContract` instead of `ArtistContract` for artist links, we need to explicitly specify to include main pictures.

**Closed by ycanardeau** 2022-01-25 14:00 UTC
