### ISSUE TITLE
"Manage" tags -button on song entries not showing up. 

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#1041] opened 2022-01-13 10:53 UTC
**Website**
VocaDB

The button for managing song tags is not visible on the entry pages. 
https://vocadb.net/Song/ManageTagUsages/{id}

For albums and artist entries, the button is correctly shown: 
![image](https://user-images.githubusercontent.com/15908050/149317047-11393975-5cfe-4dd0-a9be-94b27250ba0f.png)

**Comment by Shiroizu** [comment] 2022-01-13 10:54
Additionally, the tag dialog window (edit tags) is not movable on song entries.

**Comment by ycanardeau** [comment] 2022-01-13 14:12
Caused by #1038. Similar to #1039, I forgot to add the manage tags button.

> Additionally, the tag dialog window (edit tags) is not movable on song entries.

The [new dialog box written in React](https://github.com/VocaDB/vocadb/blob/976f104c8436ee7f34ce2feb4d87d821557e96f6/VocaDbWeb/Scripts/Components/Shared/Partials/TagsEdit.tsx) looks identical to [jQuery UI's dialog box](https://jqueryui.com/dialog/), but those two are completely different things. I decided not to implement the draggable dialog box for now, in order to simplify the conversion.  How useful was the draggable dialog box? Anyway, we could implement it later if we really need it.

**Comment by ycanardeau** [comment] 2022-01-13 14:34
Fixed by 6808c72.

**Closed by ycanardeau** 2022-01-13 14:34 UTC
Labels: React, jQuery
