### ISSUE TITLE
Only the 3 most recent comments are shown on the event pages

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#441] opened 2018-11-06 11:21 UTC
https://vocadb.net/E/1708/meikos-birthday-2018 Only three comments shown
https://vocadb.net/Comment The full thread can be viewed here (8 comments in total) 

("View all comments" missing)

**Comment by riipah** [comment] 2018-11-06 11:45
It's just not implemented yet for that page.

**Comment by riipah** [comment] 2018-12-14 11:11
Duplicate of #366

**Closed by riipah** 2018-12-14 11:11 UTC
Labels: duplicate, content: comments, content: events
