### ISSUE TITLE
Incomplete nicolog response

### ISSUE THREAD

**Issue by Shiroizu** [VocaDB/vocadb#1426] opened 2023-05-15 23:51 UTC
### Website
VocaDB

### Describe the bug
When adding PVs from nicolog, the metadata doesn't fill properly due incomplete http response.

### To Reproduce
1. Go to https://vocadb.net/Song/Edit/35711 (or any entry)
2. Try adding https://www.nicolog.jp/watch/sm20041116 as a PV
3. Observe empty title field, length, author + wrong date.

Above: correct behaviour/response
Below: incomplete response
![image](https://github.com/VocaDB/vocadb/assets/15908050/ab8dc7b9-60da-4804-8c5b-7a2efecffc79)

---

Browser console
![image](https://github.com/VocaDB/vocadb/assets/15908050/e237f05f-912a-49bd-9d19-e6e85f50ff5f)

---

Nicolog page (information exists)
![image](https://github.com/VocaDB/vocadb/assets/15908050/4b1a59e7-6a0d-495a-8715-81edb5c9eea5)

---

### Desktop (please complete the following information):
 - OS: win10
 - Browser: FireFox

Fill out the checklist. Use ~~strikethroughs~~ or leave fields empty if you don't know or are unable to check/test.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- [x] Tested on the **[beta site](https://beta.vocadb.net)**.
- ~~[ ] Checked in **Chrome**.~~
- ~~[ ] Checked in **Safari**.~~
- ~~[ ] Checked in **Edge**.~~
- ~~[ ] Checked in **Firefox**.~~
- ~~[ ] Checked in **private mode**.~~
- ~~[ ] Cleared **browser cache** and **cookies**.~~
- [x] Checked the **DevTools console**.
- [x] Checked the **syslog** (mods+ only).

Syslog:
at VocaDb.Model.Service.VideoServices.NicoLogHelper.GetVideoHtmlPage(String videoId) in C:\Sites\VocaDB\web\VocaDbModel\Service\VideoServices\NicoLogParser.cs:line 26
AuthenticationException Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'. Void MoveNext()
Win32Exception The message received was unexpected or badly formatted.
2023-05-16 02:42:54.8439 [.NET ThreadPool Worker] WARN Unable to get response for nicolog page - System.Net.Http.HttpRequestException The SSL connection could not be established, see inner exception. Void MoveNext()    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at VocaDb.Model.Service.VideoServices.NicoLogHelper.GetVideoHtmlPage(String videoId) in C:\Sites\VocaDB\web\VocaDbModel\Service\VideoServices\NicoLogParser.cs:line 26
AuthenticationException Authentication failed because the remote party sent a TLS alert: 'ProtocolVersion'. Void MoveNext()
Win32Exception The message received was unexpected or badly formatted.

**Comment by Shiroizu** [comment] 2023-05-16 00:04
It looks like this is caused by different TLS versions (1.2 & 1.3).

**Comment by FinnRG** [comment] 2023-05-20 23:23
This wasn't fixed by #1436. I'm not able to reproduce the issue locally with .NET core on linux. Maybe this is just a server configuration issue?

**Comment by FinnRG** [comment] 2023-05-27 13:16
I ran an SSL/TLS check on nicolog (https://www.ssllabs.com/ssltest/analyze.html?d=www.nicolog.jp&s=168.138.47.158), and it seems that nicolog requires cryptographic algorithms, which aren't supported on windows 7 (which I assume VocaDb uses?).

So the only way to fix this seemingly is to update to Win 10.

**Closed** 2023-07-14 20:39 UTC
Labels: content: songs, backend, weblink, .NET, adding/editing entries, backlog/on hold
