### ISSUE TITLE
Failed to submit a new song from Bilibili

### ISSUE THREAD

**Issue by sonnyding1** [VocaDB/vocadb#1796] opened 2024-07-20 06:26 UTC
### Website (required)
VocaDB

### Describe the bug (required)
I tried to upload a song with URL [https://www.bilibili.com/video/av112796041743469/](https://www.bilibili.com/video/av112796041743469/), the website said "internal server error". I think it might be because the AV number is too long.

### To Reproduce (optional)
1. Submit the song yourself.

### Checklist (required)

Fill out the checklist. Use ~~strikethroughs~~ or leave fields empty if you don't know or are unable to check/test.

- [x] Searched **[VocaDB/vocadb](https://github.com/VocaDB/vocadb/issues)** for duplicate issues.
- ~[ ] Tested on the **[beta site](https://beta.vocadb.net)**.~ can't log in
- [x] Tested on different browsers (e.g. **Firefox**, **Chrome**, **Safari**, **Edge**).
- [x] Checked in **private mode**.
- [x] Cleared **browser cache** and **cookies**.
- [x] Checked the **DevTools console**.
- ~[ ] Checked the **syslog** (mods+ only).~

**Comment by sonnyding1** [comment] 2024-07-20 06:29
I also found out there is a similar issue which is already closed #1772. Except that this AV ID is stupidly long, longer than the one in this issue.

**Comment by FinnRG** [comment] 2024-08-10 13:24
Duplicate of #1772. Will be solved with the next update.

**Closed by FinnRG** 2024-08-10 13:24 UTC
Labels: content: songs, media, weblink, adding/editing entries, external websites
