### ISSUE TITLE
"Preferred streaming service" setting broken

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#1044] opened 2022-01-14 16:09 UTC
I set my preference to YouTube but when I open a song entry, it prioritizes the NND upload first in the embed.

**Comment by ycanardeau** [comment] 2022-01-14 23:33
This was caused by #1038 ignoring `preferredVideoService`. Fixed by 0b63138.

**Closed by ycanardeau** 2022-01-14 23:33 UTC
Labels: content: songs, media

**Comment by andreoda** [comment] 2022-02-20 05:28
This is still happening. 
![grafik](https://user-images.githubusercontent.com/52045122/154829792-331d200f-2056-4aba-aff9-eab36f356c1f.png)

Should I open a new issue?

**Comment by ycanardeau** [comment] 2022-02-20 05:32
yes please
