### ISSUE TITLE
Playlist mode: Song selection not changing the PV, but updates the title

### ISSUE THREAD

**Issue by andreoda** [VocaDB/vocadb#804] opened 2021-03-09 12:19 UTC
**Website**
VocaDB

**Describe the bug**
1. When switching to another entry, only the title gets updated but not the media. It doesn't load the video.
Exception: When clicking on an entry in the playlist that has ONLY an NND upload as media, it loads. After that it is possible to click on another entry and it will load that as well but ONLY if it has a YouTube upload as one of the media linked. After that, it is not possible to load another entry again, except for it being an "ONLY NND upload". -> Cycle case
2. Autoplay doesn't work as well, even when on the site (not minimized or in the background)

Browser I am using: Firefox

https://user-images.githubusercontent.com/52045122/110469442-f31db100-80d9-11eb-8337-fffbda8e7b10.mp4

Related issues: https://github.com/VocaDB/vocadb/issues/754 and https://github.com/VocaDB/vocadb/issues/1335

**Comment by Shiroizu** [comment] 2021-03-09 12:22
The number of PV's seems to be related to this.

Entries with only one PV (piapro/nico/youtube) work fine when selected.

**Comment by ycanardeau** [comment] 2021-07-17 13:39
@andreoda Do you still experience this issue? I'm sure that this bug was present back then, but now I can't reproduce it for some reason. It could have been fixed by chance while refactoring.

**Comment by Shiroizu** [comment] 2021-07-17 13:43
@ycanardeau Still exists: 
![image](https://user-images.githubusercontent.com/15908050/126038975-cc421109-539e-4913-b5b2-a75d2a87609b.png) (I hit "next in my playlist until it happened)

**Comment by ycanardeau** [comment] 2021-07-17 13:52
@Shiroizu What browser and extensions are you using? I tried Firefox and Edge with all extensions turned off.

**Comment by Shiroizu** [comment] 2021-07-17 14:02
I managed to reproduce it on edge, which means it's probably not browser-related.

**Comment by andreoda** [comment] 2021-07-18 00:09
It seems to be fixed but I noticed something:
When the first track in the playlist is available on YouTube and NND, it will choose YouTube (probably from my preference I set on my profile settings) and when the next track is only available on NND, not YouTube, it will play that one with the NND player.
Now comes the weird part: From then on, all the following tracks will be played with the NND player, even if they are available on YouTube as well. Additionally, if I click back to the first track on the playlist, it will choose the NND video from it.

**Comment by ycanardeau** [comment] 2021-07-18 00:51
> From then on, all the following tracks will be played with the NND player, even if they are available on YouTube as well.

I haven't looked into the source code yet, but I guess it's by design in order to reduce the number of switching PV players. See also https://github.com/VocaDB/vocadb/issues/754#issuecomment-772282008.

**Comment by riipah** [comment] 2021-07-18 07:34
That is correct, the player is designed to avoid switching PVs, because loading the player may take a while, especially the Nico player, so there would be unnecessary interruption. Maybe it's not as big of a problem now than it was when the Nico player was using Flash. And of course you could consider disabling this functionality to always use the user's preference if desired and it's not too intrusive switching the player constantly.

**Comment by Shiroizu** [comment] 2021-07-25 09:26
To reproduce:

1) Go to https://vocadb.net/Profile/Shiroizu#Songs
2) Toggle off "Group by rating"
3) Click the playlist view
4) Toggle on autoplay
5) Click "next" 22 times

The title shows the entry https://vocadb.net/S/343598, but the song https://vocadb.net/S/324010 is played.

**Comment by ycanardeau** [comment] 2021-07-25 10:52
@Shiroizu Thanks for your investigation.

> What would be the best way to debug this?

I've already try to solve this issue several times, but in vain. To be honest, I haven't figured out what the cause is yet. It might be caused by several different reasons. I plan to work on this as part of #900.

**Comment by riipah** [comment] 2021-07-25 11:07
The multi-service video player is one of the most complicated and ambitious parts of VocaDB. Remember there is no other service doing this. I used to spend quite a lot of hours on it too, to get it working 95% of the time. But yes, it's annoying that sometimes it just stops. Most of the time the problems are related to unreliable detection of the player or connecting to its API. For example, loading the player dynamically using JavaScript is often not supported officially. It's also a moving target since the players keep changing, and their APIs too.

**Comment by ycanardeau** [comment] 2021-08-14 07:37
For reference, I found [React-Player](https://github.com/cookpete/react-player), which functionality is similar to VocaDB's PV player. I wonder if we could make use of it, although we need to implement some additional players (e.g. Bilibili and Creofuga).

**Comment by riipah** [comment] 2021-08-14 13:25
The current VocaDB player doesn't support Piapro I think? But NicoNico is the one with the most issues. YouTube, Vimeo, those with a proper API are easy.

**Comment by ycanardeau** [comment] 2021-08-14 15:03
> The current VocaDB player doesn't support Piapro I think?

It seems that the VocaDB player supports Piapro if `meta != null && !string.IsNullOrEmpty(meta.Timestamp)`?

https://github.com/VocaDB/vocadb/blob/dc352077711421e5d2c07a196aa427cc401b2841/VocaDbWeb/Views/Shared/Partials/PV/_EmbedPiapro.cshtml#L9

- https://vocadb.net/S/186287
- https://vocadb.net/S/150805

**Comment by riipah** [comment] 2021-08-14 15:20
I meant the frontend-based player, supporting autoplay and player switching without server embeds. Server embeds (using those Razor partials) are another matter. I think most of the playback issues are on the frontend, especially autoplay? And that doesn't support Piapro at the moment, because there is no API.

**Comment by riipah** [comment] 2021-08-14 15:22
Well actually, Piapro is using HTML5 audio element, so it would probably be possible to support that.

**Comment by ycanardeau** [comment] 2022-04-02 12:01
> What would be the best way to debug this?

@Shiroizu I've added logging everywhere in #1101 so that debugging becomes much easier (it's quite verbose though). Note that this feature is only available for the new bottom player.

Example:
![image](https://user-images.githubusercontent.com/51428094/161382134-f28dc95c-8900-4bed-9ea9-3f0fcb67d818.png)

**Comment by ycanardeau** [comment] 2022-04-02 12:03
The autoplay feature for the new bottom player has become quite stable now (some error handling is still missing though). Closing this issue for now.

**Closed by ycanardeau** 2022-04-02 12:03 UTC
Labels: API, content: songs, media, frontend, React
